# -*- coding: utf-8 -*-
"""notebook_deteccao_status_semaforo_faster_r_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yU3nZxvUVdDBjfuPAlPRWLlEFGH8j1-f
"""

!git clone https://github.com/andersonzambeli/ine_410121

# from google.colab import drive
# drive.mount('/content/drive')

import json
from google.colab import files

# List of filenames to keep
filenames_to_keep = [
    '01952.jpg', '00490.jpg', '00621.jpg', '02299.jpg', '00450.jpg', '01081.jpg',
    '00091.jpg', '00205.jpg', '02253.jpg', '01084.jpg', '01076.jpg', '00221.jpg',
    '01077.jpg', '00135.jpg', '01832.jpg', '00244.jpg', '00168.jpg', '01937.jpg',
    '00277.jpg', '00236.jpg', '00453.jpg', '00644.jpg', '02558.jpg', '01892.jpg',
    '01074.jpg', '00093.jpg', '00477.jpg', '00337.jpg', '00029.jpg', '02295.jpg',
    '01948.jpg', '00925.jpg', '02747.jpg', '00905.jpg', '02819.jpg', '00391.jpg',
    '00063.jpg', '01080.jpg', '02627.jpg', '02847.jpg', '02556.jpg', '00668.jpg',
    '00239.jpg', '00890.jpg', '00451.jpg', '00267.jpg', '01939.jpg', '00127.jpg',
    '00005.jpg', '00148.jpg', '02738.jpg', '02247.jpg', '02750.jpg', '00902.jpg',
    '01075.jpg', '02454.jpg', '02889.jpg', '02586.jpg', '00273.jpg', '00390.jpg',
    '02927.jpg', '00079.jpg', '02853.jpg', '01085.jpg', '00186.jpg', '00508.jpg',
    '02857.jpg', '00204.jpg', '00452.jpg', '00229.jpg', '00894.jpg', '00237.jpg',
    '00211.jpg', '02562.jpg', '02796.jpg', '02696.jpg', '00207.jpg', '00072.jpg',
    '01491.jpg', '00402.jpg', '00316.jpg', '02777.jpg', '01853.jpg', '00716.jpg',
    '00712.jpg', '00438.jpg', '00540.jpg', '01082.jpg', '00247.jpg', '01073.jpg',
    '01083.jpg', '00553.jpg', '01086.jpg', '02811.jpg', '00601.jpg', '01078.jpg',
    '00632.jpg', '00049.jpg', '00249.jpg', '00222.jpg', '00458.jpg', '00041.jpg',
    '00518.jpg', '01994.jpg', '02296.jpg', '00197.jpg', '02536.jpg', '02852.jpg',
    '01173.jpg', '02802.jpg', '02093.jpg', '02988.jpg', '00171.jpg', '00655.jpg',
    '01072.jpg', '00055.jpg', '00768.jpg', '00232.jpg', '00773.jpg', '00409.jpg',
    '00538.jpg', '00430.jpg', '01150.jpg', '00769.jpg', '01079.jpg', '00454.jpg',
    '00042.jpg', '00425.jpg', '00393.jpg', '02977.jpg'
]

def filter_json_by_filenames(json_data, filenames):
    filtered_annotations = [item for item in json_data['annotations'] if any(filename in item['filename'] for filename in filenames)]
    json_data['annotations'] = filtered_annotations
    return json_data

def main():
    # Upload the JSON file
    uploaded = files.upload()

    # Load the JSON data
    try:
        filename = list(uploaded.keys())[0]
        with open('/content/ine_410121/train.json', 'r') as file:
            data = json.load(file)

        # Filter the JSON data
        filtered_data = filter_json_by_filenames(data, filenames_to_keep)

        # Save the filtered data back to a JSON file
        with open('filtered_data.json', 'w') as file:
            json.dump(filtered_data, file, indent=4)

        print("Filtered data saved to 'filtered_data.json'")
    except json.JSONDecodeError as e:
        print(f"JSON decode error: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()

import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

import cv2
import time
import pandas as pd
import numpy as np
import json

from PIL import Image
import torch
import torchvision
import torchvision.transforms as T

from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torch.utils.data import DataLoader, Dataset

import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

# DIR_INPUT = '/content/drive/MyDrive/UFSC/Reconhecimento de Padrões/Visão Computacional/Trabalho Final - Reconhecimento de Padrões/Dataset/'
# DIR_IMAGES = DIR_INPUT + "train_dataset/train_images/"
# DIR_IMAGES_TEST = DIR_INPUT + "test_dataset/test_images/"

DIR_INPUT = '/content/ine_410121/'
DIR_IMAGES = DIR_INPUT + "train_images/"
# DIR_IMAGES_TEST = DIR_INPUT + "test_dataset/test_images/"

"""## Extract labels about bounding box and light color from json file"""

# with open("/content/drive/MyDrive/UFSC/Reconhecimento de Padrões/Visão Computacional/Trabalho Final - Reconhecimento de Padrões/Dataset/train_dataset/train.json") as f:
#     data_dict = json.load(f)

with open("/content/ine_410121/train.json") as f:
    data_dict = json.load(f)

# Create a list containing the data rows of the table
data = []

# Loop through the elements in the annotations list
for annotation in data_dict['annotations']:
    # Get general bounding box information
    filename = annotation['filename']
    xmin = annotation['bndbox']['xmin']
    ymin = annotation['bndbox']['ymin']
    xmax = annotation['bndbox']['xmax']
    ymax = annotation['bndbox']['ymax']

    if annotation['inbox']:
        for inbox in annotation['inbox']:
            color = inbox['color']
            data.append({
                    'filename': filename,
                    'xmin': xmin,
                    'ymin': ymin,
                    'xmax': xmax,
                    'ymax': ymax,
                    'color': color,
                })


# Create a DataFrame from a list of data and save it to a CSV file
df = pd.DataFrame(data)
df.to_csv('traffic_lights.csv', index=False)

data_tf = pd.read_csv('/content/traffic_lights.csv')

data_tf['filename'] = data_tf['filename'].str.replace('train_images\\\\', '', regex=True)
data_tf.to_csv('traffic_lights_labels.csv', index=False)

df = pd.read_csv('/content/traffic_lights_labels.csv')
df

"""## Data exploration and visualization"""

df.head()

unq_values = df["filename"].unique()
print("Total Records: ", len(df))
print("Unique Images: ",len(unq_values))

null_values = df.isnull().sum(axis = 0)
print("\n> Null Values in each column <")
print(null_values)

classes = df["color"].unique()
print("Total Classes: ",len(classes))
print("\n> Classes <\n",classes)

plt.figure(figsize=(6, 4))
plt.title('Class Distribution', fontsize= 14)
sns.countplot(x = "color", data = df);

def plot_img(image_name):

    fig, ax = plt.subplots(2, 1, figsize = (14, 14))
    ax = ax.flatten()

    bbox = df[df['filename'] == image_name]
    img_path = os.path.join(DIR_IMAGES, image_name)

    image = cv2.imread(img_path, cv2.IMREAD_COLOR)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
    image /= 255.0
    image2 = image

    ax[0].set_title('Original Image')
    ax[0].imshow(image)

    for idx, row in bbox.iterrows():
        x1 = row['xmin']
        y1 = row['ymin']
        x2 = row['xmax']
        y2 = row['ymax']
        label = row['color']
        if label == 'red':
            color_brg = (255,0,0)
        elif label == 'green':
            color_brg = (0,255,0)
        elif label == 'yellow':
            color_brg = (0,255,255)

        cv2.rectangle(image2, (int(x1),int(y1)), (int(x2),int(y2)), color_brg, 3)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(image2, label, (int(x1),int(y1-10)), font, 1, color_brg, 2)

    ax[1].set_title('Image with Bondary Box')
    ax[1].imshow(image2)

    plt.show()

# plot_img('00003.jpg')

plot_img('00005.jpg')

"""## Preparing Dataset for Training"""

_classes = np.insert(classes, 0, "background", axis=0)
class_to_int = {_classes[i] : i for i in range(len(_classes))}
int_to_class = {i : _classes[i] for i in range(len(_classes))}
print("class_to_int : \n",class_to_int)
print("\nint_to_class : \n",int_to_class)

class TrafficLightDetectionDataset(Dataset):

    def __init__(self, dataframe, image_dir, mode='train', transforms=None, resize_factor=0.25):

        super().__init__()

        self.image_names = dataframe['filename'].unique()
        self.df = dataframe
        self.image_dir = image_dir
        self.transforms = transforms
        self.mode = mode
        self.resize_factor = resize_factor

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, index: int):

        #Retrive Image name and its records (x1, y1, x2, y2, classname) from df
        image_name = self.image_names[index]
        records = self.df[self.df['filename'] == image_name]

        #Loading Image
        image = cv2.imread(self.image_dir + image_name, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
        image /= 255.0

        if self.mode == 'train':

            #Get bounding box co-ordinates for each box
            boxes = records[['xmin', 'ymin', 'xmax', 'ymax']].values

            #Getting labels for each box
            temp_labels = records[['color']].values
            labels = []
            for label in temp_labels:
                label = class_to_int[label[0]]
                labels.append(label)

            #Converting boxes & labels into torch tensor
            boxes = torch.as_tensor(boxes, dtype=torch.float32)
            labels = torch.as_tensor(labels, dtype=torch.int64)

            # Resize the image and the bounding boxes
            height, width, _ = image.shape
            new_height, new_width = int(height * self.resize_factor), int(width * self.resize_factor)
            image = cv2.resize(image, (new_width, new_height))
            boxes = boxes * self.resize_factor
            area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0])

            #Creating target
            target = {}
            target['boxes'] = boxes
            target['labels'] = labels
            target['area'] = torch.as_tensor(area, dtype=torch.float32)

            #Transforms
            if self.transforms:
                image = self.transforms(image)


            return image, target, image_name

        elif self.mode == 'test':
            # Resize the image
            height, width, _ = image.shape
            new_height, new_width = int(height * self.resize_factor), int(width * self.resize_factor)
            image = cv2.resize(image, (new_width, new_height))

            if self.transforms:
                image = self.transforms(image)

            return image, image_name

# Preparing data for Train & Validation

def get_transform():
    return T.Compose([T.ToTensor()])

def collate_fn(batch):
    return tuple(zip(*batch))


# Dataset object
dataset = TrafficLightDetectionDataset(df, DIR_IMAGES, transforms = get_transform())


# split the dataset in train and test set - using 80% for training, 20% for validation
indices = torch.randperm(len(dataset)).tolist()
train_dataset = torch.utils.data.Subset(dataset, indices[:-490])
valid_dataset = torch.utils.data.Subset(dataset, indices[-490:])


# Preparing data loaders
train_data_loader = DataLoader(
    train_dataset,
    batch_size = 1,
    shuffle = True,
    num_workers = 2,
    collate_fn = collate_fn
)


valid_data_loader = DataLoader(
    valid_dataset,
    batch_size = 2,
    shuffle = True,
    num_workers = 2,
    collate_fn = collate_fn
)

# Utilize GPU if available

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
torch.cuda.empty_cache()

"""## Create model"""

# Create / load model

# Faster - RCNN Model - pretrained on COCO
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights=None, weights_backbone=None)
num_classes = len(class_to_int)

# get number of input features for the classifier
in_features = model.roi_heads.box_predictor.cls_score.in_features

# replace the pre-trained head with a new one
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

# Preparing model for training

# Retriving all trainable parameters from model (for optimizer)
params = [p for p in model.parameters() if p.requires_grad]
# Defininig Optimizer
optimizer = torch.optim.Adam(params, lr = 0.0001)
# LR
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=2, gamma=0.1)
model.to(device)
# No of epochs
epochs = 5

len(os.listdir(r'/content/ine_410121/train_images'))

"""## Training model"""

# Training model

itr = 1
total_train_loss = []
for epoch in range(epochs):
    start_time = time.time()
    train_loss = []
    for images, targets, image_names in tqdm(train_data_loader):
        # tqdm

        # Loading images & targets on device
        images = list(image.to(device) for image in images)
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        # Forward propagation
        out = model(images, targets)
        losses = sum(loss for loss in out.values())

        # Reseting Gradients
        optimizer.zero_grad()

        # Back propagation
        losses.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1)
        optimizer.step()

        # Average loss
        loss_value = losses.item()
        train_loss.append(loss_value)

        if itr % 300 == 0:
            print(f"\n Iteration #{itr} loss: {loss_value:.4f} \n") ## {out}
        itr += 1
    lr_scheduler.step()

    epoch_train_loss = np.mean(train_loss)
    total_train_loss.append(epoch_train_loss)
    print(f'Epoch: {epoch+1}')
    print(f'Epoch train loss is {epoch_train_loss:.4f}')


    time_elapsed = time.time() - start_time
    print("Time elapsed: ",time_elapsed)

    torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': epoch_train_loss
            }, "checkpoint.pth")

plt.plot(total_train_loss)
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.show();

itr = 1
v_loss = []

start_time = time.time()

for images, targets, image_names in tqdm(valid_data_loader):

    #Loading images & targets on device
    images = list(image.to(device) for image in images)
    targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

    #Forward propagation
    out = model(images, targets)
    losses = sum(loss for loss in out.values())

    #Average loss
    loss_value = losses.item()
    v_loss.append(loss_value)

val_loss = np.mean(v_loss)
print(f'Val loss is {val_loss:.4f}')

time_elapsed = time.time() - start_time
print("Time elapsed: ",time_elapsed)

folder_path = "/content/drive/MyDrive/UFSC/Reconhecimento de Padrões/Visão Computacional/Trabalho Final - Reconhecimento de Padrões/Dataset/test_dataset/test_images"

# lấy danh sách các tệp ảnh và tạo một DataFrame trong pandas
file_names = os.listdir(folder_path)
df_test = pd.DataFrame({'filename': file_names})

df_test

# submission = pd.DataFrame(columns = ["filename", "xmin", "ymin",
#                                      "xmax", "ymax", "color"])
# submission.head()
submission = {'filename':[],'xmin':[],'ymin':[],'xmax':[],'ymax':[],'color':[]}

# Preparing Training Data
images = os.listdir(DIR_IMAGES_TEST)

df_test = df_test.drop_duplicates(subset='filename', keep="first")

# Test Dataset
test_dataset = TrafficLightDetectionDataset(df_test, DIR_IMAGES_TEST, mode = 'test',
                                            transforms = get_transform())

# Test data loader
test_data_loader = DataLoader(
    test_dataset,
    batch_size=2,
    shuffle=False,
    num_workers=2,
    drop_last=False,
    collate_fn=collate_fn
)

# Results - may take few mins, please wait!

threshold = 0.7
model.eval()

for images, image_names in test_data_loader:

    # Forward ->
    images = list(image.to(device) for image in images)
    output = model(images)

    # Converting tensors to array
    boxes = output[0]['boxes'].data.cpu().numpy()
    scores = output[0]['scores'].data.cpu().numpy()
    labels = output[0]['labels'].data.cpu().numpy()

    # Thresholding
    boxes_th = boxes[scores >= threshold].astype(np.int32)
    scores_th = scores[scores >= threshold]

    # int_to_class - labels
    labels_th = []

    for x in range(len(labels)):
        if scores[x] > threshold:
            labels_th.append(int_to_class[labels[x]])
    #Appending results to csv
    for y in range(len(boxes_th)):

        #Bboxes, classname & image name
        x1 = boxes_th[y][0] * 4
        y1 = boxes_th[y][1] * 4
        x2 = boxes_th[y][2] * 4
        y2 = boxes_th[y][3] * 4
        class_name = labels_th[y]


        # Creating row for df
        row = {"filename" : image_names[0],
               "xmin" : x1, "xmax" : x2,
               "ymin" : y1, "ymax" : y2,
               "color" : class_name}

        # Appending to df
        # submission = submission.append(row, ignore_index = True)
        for key in row:
          submission[key].append(row[key])
        # submission = pd.concat([submission,pd.DataFrame(row)])

# submission = pd.DataFrame(submission)

submission = pd.DataFrame(submission)
print(submission)

submission.to_csv('submission.csv', index = False)

df = pd.read_csv('/content/submission.csv')
df.head(15)

DIR_INPUT = '/content/drive/MyDrive/UFSC/Reconhecimento de Padrões/Visão Computacional/Trabalho Final - Reconhecimento de Padrões/Dataset/'

DIR_IMAGES = DIR_INPUT + "train_dataset/train_images/"
DIR_IMAGES_TEST = DIR_INPUT + "test_dataset/test_images/"

def plot_img_test(image_name):

    fig, ax = plt.subplots(2, 1, figsize = (14, 14))
    ax = ax.flatten()

    bbox = df[df['filename'] == image_name]
    img_path = os.path.join(DIR_IMAGES_TEST, image_name)

    image = cv2.imread(img_path, cv2.IMREAD_COLOR)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
    image /= 255.0
    image2 = image

    ax[0].set_title('Original Image')
    ax[0].imshow(image)

    for idx, row in bbox.iterrows():
        x1 = row['xmin']
        y1 = row['ymin']
        x2 = row['xmax']
        y2 = row['ymax']
        label = row['color']
        if label == 'red':
            color_brg = (255,0,0)
        elif label == 'green':
            color_brg = (0,255,0)
        elif label == 'yellow':
            color_brg = (0,255,255)

        cv2.rectangle(image2, (int(x1),int(y1)), (int(x2),int(y2)), color_brg, 3)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(image2, label, (int(x1),int(y1-10)), font, 1, color_brg, 2)

    ax[1].set_title('Image with Bondary Box')
    ax[1].imshow(image2)

    plt.show()

plot_img_test('00007.jpg')